### ISSUE TITLE
Document where SPARQL queries should be run

### ISSUE THREAD

**Issue by cthoyt** [egonw/jats#1]
https://github.com/egonw/jats/blob/main/queries/allPaper.rq doesn't self-document against which endpoint it should be run. I think there's a semi-standard way of doing this, like I did in https://github.com/labsyspharm/labsyspharm-wikidata/blob/main/group-works.sparql

**Comment by egonw** [comment]
There is no SPARQL endpoint. This is just the SPARQL you run on the RDF. I'll add a command line example asap.

**Comment by cthoyt** [comment]
Ahh yeah so I read the makefile and figured this out, but it wasn't super obvious. maybe you can use some folders to organize the repo so the makefile doesn't get lost

**Comment by egonw** [comment]
not every github repository is ready for dissemination... many of my repositories are just electronic lab notebooks. they're for me. I don't think we have an standard yet to mark a repository as a lab notebook, afaik.

**Comment by egonw** [comment]
I'll leave it open, because it's still good to document how to do it anyway.

**Comment by egonw** [comment]
I added a comment in the SPARQL file. Also see the `Makefile` which documents it in detail how to use it.
